/** Friendly Hebrew copy for the owner onboarding wizard (non-technical tone). */
export const heOnboarding = {
  bannerPrompt: "עוד רגע — סיימו את ההגדרה כדי לקבל קישור לקביעת תורים.",
  bannerCta: "המשך הגדרה",
  bannerDismiss: "הסתרה",
  step1: "פרטי עסק",
  step2: "קביעת תורים",
  step3: "שירות ולקוח",
  step4: "מוכנים לשתף",
  loading: "טוענים…",
  needLogin: "כדי להמשיך בהגדרה צריך להתחבר לחשבון.",
  goLogin: "מעבר להתחברות",
  title1: "בואו נכיר את העסק",
  sub1: "כמה פרטים — ואפשר להמשיך. אפשר לשנות הכל אחר כך בהגדרות.",
  title2: "מתי לקוחות יכולים לקבוע?",
  sub2: "בוחרים ימים ואורך תור. זה מה שהלקוחות יראו בדף ההזמנה.",
  title3: "נוסיף דוגמה אחת",
  sub3: "שירות עם מחיר ולקוח לדוגמה — כדי שיהיה מה לראות ברשימות. אפשר למחוק או לערוך בשנייה.",
  title4: "הדף שלכם מוכן",
  sub4: "שולחים את הקישור ללקוחות — הם קובעים לבד בלי שיחות מיותרות.",
  fieldBusinessType: "סוג העסק",
  fieldBusinessName: "שם העסק",
  phBusinessName: "למשל: בית ספר לנהיגה כיף",
  fieldPhone: "טלפון ליצירת קשר",
  fieldSlug: "כתובת קצרה לדף ההזמנה (באנגלית)",
  hintSlug: "רק אותיות באנגלית, מספרים ומקף. זה יופיע בקישור שתשלחו ללקוחות.",
  fieldWorkStart: "תחילת יום עבודה",
  fieldWorkEnd: "סוף יום עבודה",
  fieldWorkDays: "באיזה ימים אתם פתוחים?",
  fieldSlot: "אורך כל תור (ברירת מחדל)",
  minutes: "דקות",
  publishBooking: "לפרסם את דף ההזמנה — לקוחות יוכלו לבחור מועד לבד",
  blockService: "שירות ראשון",
  fieldServiceName: "שם השירות",
  fieldServicePrice: "מחיר (₪)",
  blockClient: "לקוח לדוגמה",
  fieldClientName: "שם מלא",
  fieldClientPhone: "טלפון",
  yourLink: "הקישור שלכם לקביעת תור",
  copyLink: "העתקת הקישור",
  copied: "הועתק ללוח",
  copyFailed: "לא הצלחנו להעתיק — בחרו והעתיקו ידנית",
  shareWhatsapp: "שיתוף בוואטסאפ",
  whatsappShareText: (url: string) =>
    `היי! אפשר לקבוע תור פה, בלי טלפונים: ${url}`,
  goDashboard: "כניסה לדף הבית",
  noSlugYet: "לא הצלחנו לטעון את הקישור — תמצאו אותו בהגדרות.",
  back: "חזרה",
  next: "המשך",
  skipForNow: "אמשיך מאוחר יותר — מעבר לדף הבית",
  errBusinessName: "נא למלא שם עסק (לפחות שני תווים).",
  errPhone: "נא למלא מספר טלפון תקין.",
  errSlug: "בחרו כתובת קצרה באנגלית (לפחות 2 תווים).",
  errDays: "בחרו לפחות יום אחד.",
  errServiceName: "נא למלא שם שירות.",
  errServicePrice: "נא למלא מחיר תקין.",
  errClientName: "נא למלא שם לקוח.",
  errClientPhone: "נא למלא טלפון ללקוח.",
  errGeneric: "משהו השתבש. נסו שוב.",
  errSettings: "לא נטענו ההגדרות. נסו לרענן.",
  errAvailability: "לא נטענה זמינות. נסו לרענן.",
};
